pipeline:
  test:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/go-base:1.13.0-gcc-golint
    commands:
      - go test -mod=vendor ./...

  lint:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/go-base:1.13.0-gcc-golint
    commands:
      - ./scripts/linters.sh

  check-go-modules:
    image: 258875347723.dkr.ecr.us-east-1.amazonaws.com/go-base:1.13.0-gcc-golint
    commands:
      - go mod tidy
      - go mod vendor
      - git status
      - git diff
      - test -z "$(git status --porcelain)"
